### ISSUE TITLE
how to fix for private vimeo video 

### ISSUE THREAD

**Issue by Nuwaithu** [superm0/HCVimeoVideoExtractor#1]

**Comment by superm0** [comment]
Can you share a private video url?

**Comment by dhritzkiv** [comment]
Here is an example private vimeo video: https://vimeo.com/359413330/bff920d0e6

A lot of the information can be parsed from the meta tags on the page, as well as the oembed endpoint: https://vimeo.com/api/oembed.json?url=https%3A%2F%2Fvimeo.com%2F359413330%2Fbff920d0e6

Not sure about API access.

However, it seems as though removing the final ID (i.e. resulting in https://player.vimeo.com/video/359413330) from the path and accessing the API with that ID works.

**Comment by superm0** [comment]
@Nuwaithu the library has been updated, please try again using `fetchVideoURLFrom:id`
