### ISSUE TITLE
Failed to retrive mp4 video url

### ISSUE THREAD

**Issue by thathsara-senarathne-azbow** [superm0/HCVimeoVideoExtractor#19]
Error Domain=ph.hercsoft.HCVimeoVideoExtractor Code=4 "Failed to retrive mp4 video url" UserInfo={NSLocalizedDescription=Failed to retrive mp4 video url, NSLocalizedFailureReason=Failed to retrive mp4 video url}
<img width="959" alt="Screenshot 2024-04-18 at 12 43 19" src="https://github.com/superm0/HCVimeoVideoExtractor/assets/141614500/f37bebe3-5cc4-4f64-b874-24353fe1e25b">

**Comment by superm0** [comment]
@thathsara-senarathne-azbow kindly try the latest version 0.0.5 if this issue is resolved.
