### ISSUE TITLE
How to play my private video? (Private vimeo video link)

### ISSUE THREAD

**Issue by cemalsayin** [superm0/HCVimeoVideoExtractor#3]
Hello, I have private vimeo video link. Can i use it with that pod? Link example in bellow i can play it in browser but when i use link with pod file it turns "Error = Failed to parse Vimeo response"

https://vimeo.com/230611000/xxxxxxx

**Comment by budidino** [comment]
@cemalsayin I know it's a late reply but maybe it will help someone else. I had the same issue and fixed it by using `fetchVideoURLFrom id` instead of `fetchVideoURLFrom url`... and in that case just pass the `230611000` as `id`

**Comment by nithintwobase** [comment]
@budidino I am still facing the same issue tried both fetchVideoURLFrom id & fetchVideoURLFrom URL. But the issue is not fixed. Have you done any other changes?

**Comment by superm0** [comment]
@nithintwobase the library has been updated, please try again using `fetchVideoURLFrom:id`

**Comment by naariman** [comment]
> @nithintwobase the library has been updated, please try again using `fetchVideoURLFrom:id`

hi is that work? It's still a problem.
